[project]
name = "jobscout"
version = "0.1.0"
requires-python = ">=3.14"

[tool.pytest.ini_options]
testpaths = ["tests"]
pythonpath = [".", "tests"]

[tool.ruff]
line-length = 100

[tool.ruff.lint]
extend-select = ["D"]  # docstrings

[tool.ruff.lint.pydocstyle]
convention = "google"

[tool.ruff.lint.per-file-ignores]
"tests/**" = ["D"]

[tool.pyright]
venvPath = "."
venv = ".venv"
